# docker-compose.yml
version: '3.8'

services:
  sign-translator:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./static:/app/static
      - ./cache:/app/cache
    restart: unless-stopped
